services:
  ollama:
    image: ollama/ollama:0.9.0
    volumes:
      - ./volumes/ollama:/root/.ollama
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  python-dev:
    image: python-dev
    build:
      dockerfile: docker/Dockerfile
      context: ../
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    command: bash -c "sleep infinity"
    user: ${USER_UID}:${USER_GID}
    volumes: 
      - ../:/workspace
